spring.application.name=Day23
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true


#spring.security.user.name=admin
#spring.security.user.password=admin@123

spring.profiles.active=dev

